name: CI – HTML Validate

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install html-validator
        run: npm install -g html-validator-cli
      - name: Validate index.html
        run: html-validator-cli --file=index.html --verbose
